#!/usr/bin/env python

import sys
import wye

url = "http://localhost:8080"

context = wye.Context(url)

job = context.define_job(name="job1", description="A test job")

sink = job.define_python_worker("sink", "go-sink.py", parallelism=2)
sink2 = job.define_python_worker("sink2", "go-sink.py", parallelism=2)

trans1 = job.define_python_worker("trans1", "go-t1.py", parallelism=2)
trans1.connect("output", [(sink,"input"),(sink2,"input")])

trans2 = job.define_python_worker("trans2", "go-t2.py", parallelism=2)
trans2.connect("output", [(sink,"input"),(sink2,"input")])

src = job.define_python_worker("source", "go-source.py")
src.connect("output", [(trans1,"input"),(trans2,"input")])

job_id = job.implement()

sys.stderr.write("Job %s is running.\n" % job_id)

